export const GET_TODOS_REQUEST = "GET_TODOS_REQUEST";
export const GET_TODOS_ERROR = "GET_TODOS_ERROR";
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";

export const DELETE_TODO = "DELETE_TODO";
export const COMPLETE_TODO="COMPLETE_TODO";
export const ADD_TODO="ADD_TODO";


